### ISSUE TITLE
error when connecting to eternl

### ISSUE THREAD

**Issue by adrem1** [pbwebdev/cardanopress#18]
Hi,

I have been in touch with @pbwebdev on Twitter, but thought it best to leave this info here as well. 

I am trying to integrate cardanopress into an AWS self hosted wordpress instance running the Astra theme.  I followed the instructions on https://cardanopress.io/docs/configuring-the-server-for-cardanopress/ and have had no issues getting the Wallet Connect button to show up and editing the Connect Modal with custom CSS (see attached 01.png).

However, when the connector correctly detects Eternl as the (only available) browser extension and I try to connect to Eternl I get a compile error in the page (attached image 02.png) and the console error attached (03.png). 

The .htaccess file is loading correctly and includes the wasm application: I have checked this by deliberately coding nonsense into the .htaccess file and got an apache server error. 

Do you have any suggestions?

**Comment by pbwebdev** [comment]
You've got a few issues going on here and we'll have to debug one at a time to get to the final issue and solution.

Firstly, get https working.

Second, the WASM file there is missing. Your server looks like it isn't delivering the WASM file.
Make sure that WASM file type is enabled. 

Double check that the file is in that path too while we are at it.

**Comment by adrem1** [comment]
Hi Pete,

well, that was a quick one! Enabling HTTPS did the trick, no other mods needed. Sorry for wasting your time!
