### ISSUE TITLE
OpenLitespeed Server enable .wasm mimetype

### ISSUE THREAD

**Issue by kleozzy** [pbwebdev/cardanopress#3]
Hello folks,

I am currently running on Openlitespeed server which is an apache based http-service.
Does anyone know how to properly edit the .htaccess file to support .wasm?
I did try adding the line given in docs but it doesn't work for me.
i tried adding the suggested link in both the main .htaccess and one in the same folder as the wasm but no results.

**Comment by pbwebdev** [comment]
@kleozzy adding MIME types on litespeed servers is different to htaccess and apache.

Follow this please:
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:config:add-mime-type#:~:text=How%20to%20add%20MIME%20type,Restart%20LSWS
