### ISSUE TITLE
Dashboard template - Displaying public addr by username

### ISSUE THREAD

**Issue by Dett0x** [pbwebdev/cardanopress#4]
Hi Pete,
Displaying public addr by username as discussed on discord.
End goal is to use wallet connector with poll maker plugin.
Giving the user voting power based on balance (policy id specific) to vote on the poll.
Best regards,

**Comment by kleozzy** [comment]
I would vote for this as well , crucial for DAO.

**Comment by pbwebdev** [comment]
Yeh no problem.

In regards to the public address, I don't think we'll use that as the username. We may pull it in as another identifier field in the user profile if the user wants to make it public.

As for the voting process, we're looking into it. We need to find a good plugin to use or something that is flexible for the voting requirements.

1 vote per user, voting power based on wallet balance of total specified token.

We'll also have to extend out the global settings to include a Governance panel.

**Comment by Dett0x** [comment]
I suggest the plugin : [WordPress Poll maker by Poll Maker Team.]
(https://wordpress.org/plugins/poll-maker/)

**Comment by kermage** [comment]
Version 0.28.0 added the support for ADA Handle https://adahandle.com/.

Please check the governance plugin at https://github.com/CardanoPress/plugin-governance
