### ISSUE TITLE
Delegation template - Displaying details

### ISSUE THREAD

**Issue by Dett0x** [pbwebdev/cardanopress#6]
Hi Pete,

Could you display the following on the delegation template for connected user whom are already staked to the pool ID : 
Staked balance of connected user
Delegation history ~6 epochs (1 month)  of connected user
Pool active stake
Pool Live stake 

Best regards,
Dettox

**Comment by kermage** [comment]
Please check the page template [Delegation.php](https://github.com/CardanoPress/cardanopress/blob/a1d761731bb9bf62bc3cc9b3a7fa5cf4cac0bec3/templates/page/Delegation.php) you can customize in your current theme
