### ISSUE TITLE
Connect-Wallet Shortcode

### ISSUE THREAD

**Issue by NilsDannemann** [pbwebdev/cardanopress#7]
Hi Pete,

working on a small side-project here: 
https://baa409q.myraidbox.de/ (later: cardanopick.com)

I think this plugin needs shortcodes. 
For example to place the connect-wallet-link in the header: https://cln.sh/TlEv3G

It's out of scope for this github-issue, but I'd suggest finding a way to make the individual pages more modular (e.g. via shortcode). That way you immediately have full Elementor Support / Page Builder Support. Then people could build their own dashboards views.

Ideally for me would be something like this: https://cln.sh/Bmziji

**Comment by NilsDannemann** [comment]
Oh and great work and idea with the plugin. Happy to support this

**Comment by kermage** [comment]
There is already a working implementation of shortcode for templates I made

Try this for the connect button ```[cardanopress_template name="part/modal-trigger"]```

**Comment by pbwebdev** [comment]
@NilsDannemann I have to do all the documentation that lists all the shortcodes and parts.
