### ISSUE TITLE
CNFT - front end

### ISSUE THREAD

**Issue by MattVurtly** [pbwebdev/cardanopress#8]
H any plans to make a CNFT front end to allow sale of NFT connect to a wallet, if there is a smart contract ?

**Comment by pbwebdev** [comment]
Hey @MattVurtly 
You can use the frontend Payment page layout as the NFT minting page. You will need to provide the minting engine though. We don't do that. There are a few projects that take care of that side of things and you can use the plugin as the frontend interface for it all.
